#!/bin/bash

PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

TIMESTR=`date +"%y%m%d"`
NAME=`hostname`
BACKUPFILE="/tmp/${NAME}_files_$TIMESTR.tar.gz"

tar -cPp --use-compress-program=pigz -f $BACKUPFILE  /home/forge
aws s3 cp $BACKUPFILE s3://cloudhipsters.backup/ --only-show-errors
rm -rf $BACKUPFILE
